In [1]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.21.5


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [2]:
# YOUR CODE STARTS HERE
arr=np.full((2, 3), 5)
# YOUR CODE ENDS HERE
print(arr)

[[5 5 5]
 [5 5 5]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [3]:
# YOUR CODE STARTS HERE
rand_arr=np.random.rand(2, 3)
# YOUR CODE ENDS HERE
print(rand_arr)

[[0.07531495 0.21069349 0.87497892]
 [0.04299628 0.57090416 0.54652015]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value

In [4]:
#YOUR CODE STARTS HERE
arr_sum=np.sum(rand_arr)
arr_mean=np.mean(rand_arr)
arr_max=np.max(rand_arr)
arr_min=np.min(rand_arr)
#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 2.321407950704144
mean: 0.38690132511735736
max: 0.8749789174808632
min:0.042996281094153654


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [5]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
print(f'Indices of max value: {np.unravel_index(np.argmax(arr, axis=None), arr.shape)}')
print(f'Indices of min value: {np.unravel_index(np.argmin(arr, axis=None), arr.shape)}')
#Find the indices of maximum and minimum value along each of its columns.
print(f'Max value along columns: {np.max(arr,axis=0)}')
print(f'Min value along columns: {np.min(arr,axis=0)}')
#Find the indices of maximum and minimum value along each of the its rows.
print(f'Max value along rows: {np.max(arr,axis=1)}')
print(f'Min value along rows: {np.min(arr,axis=1)}')
#YOUR CODE ENDS HERE

Array:
[[ 5 12 51 25]
 [25 29  2 27]]

Indices of max value: (0, 2)
Indices of min value: (1, 2)
Max value along columns: [25 29 51 27]
Min value along columns: [ 5 12  2 25]
Max value along rows: [51 29]
Min value along rows: [5 2]
